language: node_js
node_js:
  - "8"
  - "9"
cache: npm
install: npm install
script: true
jobs:
  include:
    - stage: npm release
      node_js: "8"
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_KEY"
        skip_cleanup: true
        on:
          tags: true
